### ISSUE TITLE
SerializationExceptions thrown during execution of unit tests

### ISSUE THREAD

**Issue by viciousviper** [dokan-dev/dokan-dotnet#10]
Get rid of the SerializationExceptions that are sometimes thrown during unit test execution:

> Unhandled Exception: System.Runtime.Serialization.SerializationException: Unable to find assembly 'Moq, Version=4.2.1507.118, Culture=neutral, PublicKeyToken=69f491c39445e920'.
>    at System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.GetAssembly()
>    at System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType(BinaryAssemblyInfo assemblyInfo, String name)
>    at System.Runtime.Serialization.Formatters.Binary.ObjectMap..ctor(String objectName, String[] memberNames, BinaryTypeEnum[] binaryTypeEnumA, Object[] typeInformationA, Int32[] memberAssemIds, ObjectReader objectReader, Int32 objectId, BinaryAssemblyInfo assemblyInfo, SizedArray assemIdToAssemblyTable)
>    at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record)
>    at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(BinaryHeaderEnum binaryHeaderEnum)
>    at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
>    at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
>    at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
>    at System.Runtime.Remoting.Channels.CrossAppDomainSerializer.DeserializeObject(MemoryStream stm)
>    at System.AppDomain.Deserialize(Byte[] blob)
>    at System.AppDomain.UnmarshalObject(Byte[] blob)

see here: http://stackoverflow.com/questions/24675922/how-to-avoid-serializationexception-warnings-with-vstest-console-exe-and-moq for a possible solution

**Comment by viciousviper** [comment]
- No `SerializationExceptions` occured since at least beginning of November.
- Locally executed tests as well as AppVeyour test execution successful for https://github.com/dokan-dev/dokan-dotnet/pull/43

-> **Closed**
