### ISSUE TITLE
Can't install the Dokan driver

### ISSUE THREAD

**Issue by qiandi** [dokan-dev/dokan-dotnet#315]
Windows version: windows 10 19044
Processor architecture: X64
Dokany version: exe 2.0.1.2000
Net Core version: 3.1

> 2022-09-20 14:37:19.945|Fatal|1|Can't install the Dokan driver
DokanNet.DokanException: Can't install the Dokan driver
   at DokanNet.Dokan.CreateFileSystem(IDokanOperations operations, String mountPoint, DokanOptions mountOptions, Boolean singleThread, Int32 version, TimeSpan timeout, String uncName, Int32 allocationUnitSize, Int32 sectorSize, ILogger logger)
   at DokanNet.Dokan.CreateFileSystem(IDokanOperations operations, String mountPoint, DokanOptions mountOptions, Boolean singleThread, Int32 version, ILogger logger)
   at DokanNet.Dokan.CreateFileSystem(IDokanOperations operations, String mountPoint, DokanOptions mountOptions, Boolean singleThread, ILogger logger)
   at DokanNet.Dokan.CreateFileSystem(IDokanOperations operations, String mountPoint, DokanOptions mountOptions, ILogger logger)

**It happens every once in a while, restarting the computer can't solve it, you have to reinstall the driver.**

**Comment by Liryna** [comment]
Hi @qiandi ,

Please enable debug logs when it happens. It would give the reason why it happened.

**Comment by Liryna** [comment]
Close for inactivity
